# fly.toml app configuration file generated for pomodoro-analytics on 2023-07-29T00:11:06+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pomodoro-analytics"
primary_region = "syd"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
